apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  selector:
    matchLabels:
      app: poi
  replicas: 1
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - image: "registryyad4447.azurecr.io/paoloceffa/poi:1.0"
        name: poi
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "0.2"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        envFrom:
        - secretRef:
            name: sql
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
        - name: "CONFIG_FILES_PATH"
          value: "/secrets"
        - name: "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT"
          value: "false"
        - name: "WEB_SERVER_BASE_URI"
          value: "http://0.0.0.0"
        - name: "WEB_PORT"
          value: "80"

---

apiVersion: v1
kind: Service
metadata:
  name: poi-service
  labels:
    run: poi-service
spec:
  selector:
    app: poi
  ports:
  - name: poi-http
    protocol: TCP
    port: 80
    targetPort: 80
