apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsdata
  namespace : playground
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: aksmystyad4447.file.core.windows.net
    path: /aksmystyad4447/export