apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsdata
  namespace : playground
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: aksmystymi6049.file.core.windows.net
    path: /aksmystymi6049/export