apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsdataclaim
  namespace : playground
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs