apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  labels:
    app: trips
spec:
  selector:
    matchLabels:
      app: trips
  replicas: 1
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - image: "registryufe8262.azurecr.io/paoloceffa/trips"
        name: trips
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "0.2"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        env:
        - name: "PORT"
          value: "80"
        - name: "CONFIG_FILES_PATH"
          value: "/secrets"
        - name: "SQL_USER"
          value: "sqladminuFe8262"
        - name: "SQL_PASSWORD"
          value: "pG0ot9Zc1"
        - name: "SQL_SERVER"
          value: "sqlserverufe8262.database.windows.net"
        - name: "SQL_DBNAME"
          value: "mydrivingDB"
        - name: "OPENAPI_DOCS_URI"
          value: "0.0.0.0"

---

apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  selector:
    app: trips
  ports:
  - name: trips
    protocol: TCP
    port: 80
    targetPort: 80